# Builds inst/atlas_registry.rds: one row per atlas exported by an installed
# ggsegverse package. Run after installing or updating atlas packages.

library(ggseg.formats)

core_package <- "ggseg.formats"

registry_packages <- function() {
  deployable <- rownames(available.packages(
    repos = "https://ggsegverse.r-universe.dev"
  ))
  installed <- rownames(installed.packages())
  atlas_pkgs <- intersect(grep("^ggseg[A-Z]", installed, value = TRUE), deployable)
  c(core_package, sort(atlas_pkgs))
}

# Deprecated aliases (e.g. hoCort() for ho_cort()) signal with a lifecycle
# warning on call; they duplicate their replacement and are dropped.
call_atlas <- function(fn) {
  deprecated <- FALSE
  atlas <- withCallingHandlers(
    tryCatch(fn(), error = function(e) NULL),
    lifecycle_warning_deprecated = function(w) {
      deprecated <<- TRUE
      invokeRestart("muffleWarning")
    }
  )
  if (deprecated) NULL else atlas
}

atlas_entries <- function(pkg) {
  ns <- asNamespace(pkg)
  entries <- lapply(getNamespaceExports(pkg), function(nm) {
    fn <- get(nm, envir = ns)
    if (!is.function(fn) || length(formals(fn)) > 0) return(NULL)
    atlas <- call_atlas(fn)
    if (is.null(atlas) || !is_ggseg_atlas(atlas)) return(NULL)
    describe_atlas(atlas, pkg, nm)
  })
  do.call(rbind, Filter(Negate(is.null), entries))
}

describe_atlas <- function(atlas, pkg, object) {
  data.frame(
    package = pkg,
    object = object,
    atlas = atlas$atlas,
    type = atlas_type(atlas),
    n_regions = length(atlas_regions(atlas)),
    n_labels = length(atlas_labels(atlas)),
    hemispheres = paste(sort(unique(atlas$core$hemi)), collapse = ","),
    views = paste(atlas_views(atlas), collapse = ","),
    has_2d = !is.null(atlas_sf(atlas)),
    has_3d = has_3d_data(atlas),
    stringsAsFactors = FALSE
  )
}

has_3d_data <- function(atlas) {
  !is.null(atlas$data$vertices) ||
    !is.null(atlas$data$meshes) ||
    !is.null(atlas$data$centerlines)
}

registry <- do.call(rbind, lapply(registry_packages(), atlas_entries))
registry <- registry[order(registry$type, registry$atlas), ]
rownames(registry) <- NULL

saveRDS(registry, "data/atlas_registry.rds")
message(nrow(registry), " atlases from ",
        length(unique(registry$package)), " packages")
print(table(registry$type))

# R/atlas_packages.R is generated rather than hand-written so the app attaches
# exactly the packages the registry draws on. The calls are spelled out one by
# one because rsconnect reads them statically when building manifest.json.
atlas_pkgs <- setdiff(sort(unique(registry$package)), core_package)
writeLines(
  c(
    "# Generated by data-raw/build_registry.R -- do not edit by hand.",
    "# Attaching the atlas packages lets the app evaluate its generated",
    "# snippets verbatim, exactly as a user would run them.",
    "",
    paste0("library(", atlas_pkgs, ")")
  ),
  "R/atlas_packages.R"
)
message("wrote R/atlas_packages.R (", length(atlas_pkgs), " packages)")
