# Generated by data-raw/build_registry.R -- do not edit by hand.
# Attaching the atlas packages lets the app evaluate its generated
# snippets verbatim, exactly as a user would run them.

library(ggsegAAL)
library(ggsegAicha)
library(ggsegArslan)
library(ggsegAtlasTrack)
library(ggsegBrainnetome)
library(ggsegCerebellum)
library(ggsegChen)
library(ggsegFreeSurfer)
library(ggsegGlasser)
library(ggsegGordon)
library(ggsegHistorical)
library(ggsegHO)
library(ggsegIca)
library(ggsegJHU)
library(ggsegMiccai)
library(ggsegPower)
library(ggsegSchaefer)
library(ggsegYeo2011)
